### ISSUE TITLE
Failure to download image from Digikey

### ISSUE THREAD

**Issue by benpayne** [EUdds/Digikey-Inventree-Integration#5]
I have recently setup inventree and found this very helpful tool.  Been playing with it today and all is working great, except downloading of images from digikey.  I see the following error, but on inspection I see that it's failing to download the image.  It's getting a 403 error code.  I have downloaded the image from a browser with no issues.  I thought maybe I had some cached authentication in the browser cache.  So I tried a browser that I've not used to log into digikey and it also downloaded just fine.  So a bit puzzled why the script would fail with a 403.  

```
Trying URL https://mm.digikey.com/Volume0/opasdata/d220001/medias/images/5565/MFG_PI_5_HERO.jpg
<Response [403]>
ERROR: Request code is 403
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/bpayne/wip/inventory/Digikey-Inventree-Integration/inventree_digikey/__main__.py", line 23, in <module>
    add_digikey_part(dkpart)
  File "/Users/bpayne/wip/inventory/Digikey-Inventree-Integration/inventree_digikey/Inventree.py", line 27, in add_digikey_part
    inv_part = create_inventree_part(dkpart)
  File "/Users/bpayne/wip/inventory/Digikey-Inventree-Integration/inventree_digikey/Inventree.py", line 81, in create_inventree_part
    upload_picture(dkpart, part)
  File "/Users/bpayne/wip/inventory/Digikey-Inventree-Integration/inventree_digikey/Inventree.py", line 121, in upload_picture
    invPart.uploadImage(img_file)
  File "/Users/bpayne/wip/inventory/venv/lib/python3.9/site-packages/inventree/base.py", line 543, in uploadImage
    raise TypeError(f"uploadImage called with invalid image: '{image}'")
TypeError: uploadImage called with invalid image: '-1'
```

**Comment by benpayne** [comment]
I suspect this has something to do with digikeys CDN provider Akamai and their validation of a "real" browsers.  I get this error with a python test program that just uses requests, I also get this error with curl.  Interesting I don't get this error with wget, or a real browser.  I'm guessing were just missing some headers in the request.  But haven't found the right ones yet...

**Comment by benpayne** [comment]
Here's an interesting thread about others having issues with Akamai servers an another http library.

https://github.com/aio-libs/aiohttp/issues/5643

**Comment by benpayne** [comment]
Interestingly I've found that using http.client library directly does work fine.  The code is a little more complex (but not too much).  But it doesn't seem to create an error, at least in my test code.  I'm importing this into the code and will test it a bit.  If it look good I'll send a pull request.

**Comment by benpayne** [comment]
I've create a pull request with the changes to use http.client.
